server:
  port: 3000
  node_env: production

ollama:
  # base_url: "http://production-ollama:11434" I think not requird we are going to register it on Eureka 
  model: "qwen2.5-coder:7b"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurekaUser}:${eurekaPass}@${eurekaIp}:${eurekaPort}/eureka/

logging:
  level: info
